## 1. Import the Required Libraries

In [1]:
import tensorflow as tf 
import matplotlib.pyplot as plt 
import pandas as pd
import seaborn as sns 
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten
from tensorflow.keras.models import Sequential

## 2. Data Preprocessing

### 2.1 Training Images Preprocessing 

In [2]:
# Path to training dataset directory
train_dir = r"New-Cattle-Diseasee-3/train"

In [3]:
# Load the dataset
training_set = image_dataset_from_directory(
    directory=train_dir,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=42,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False
)

Found 2518 files belonging to 8 classes.


# 2.2 Validation Image Preprocessing

In [4]:
valid_dir = r"New-Cattle-Diseasee-3/valid"

In [5]:
validation_set = image_dataset_from_directory(
    directory=valid_dir,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=42,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False
)

Found 575 files belonging to 8 classes.


In [6]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 8), dtype=tf.float32, name=None))>

In [7]:
for x,y in training_set:
    print(x, x.shape)
    print(y, y.shape)
    break

tf.Tensor(
[[[[154.42188  158.42188  144.42188 ]
   [159.14062  162.14062  153.14062 ]
   [136.5      137.75     132.25    ]
   ...
   [144.92188  134.92188  124.921875]
   [142.1875   132.1875   122.1875  ]
   [138.5      130.5      119.5     ]]

  [[141.23438  145.1875   131.32812 ]
   [138.48438  139.48438  131.48438 ]
   [147.67188  146.92188  142.3125  ]
   ...
   [131.9375   121.921875 112.96875 ]
   [149.54688  139.53125  130.57812 ]
   [144.53125  135.53125  126.625   ]]

  [[168.57812  170.78125  159.54688 ]
   [155.65625  155.78125  147.78125 ]
   [152.59375  150.20312  144.82812 ]
   ...
   [132.92188  122.03125  115.921875]
   [146.70312  135.8125   129.70312 ]
   [142.125    131.375    125.75    ]]

  ...

  [[204.10938  181.10938  149.10938 ]
   [215.79688  192.79688  160.79688 ]
   [202.45312  179.45312  147.45312 ]
   ...
   [ 79.671875  49.421875  25.296875]
   [134.79688  102.796875  79.546875]
   [139.82812  104.953125  82.578125]]

  [[195.25     172.25     140.25  

## 3. Building the Model 

In [8]:
model = Sequential()

### 3.1 Building the Convolution Layer 

In [9]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [10]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [11]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [12]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [13]:
model.add(Flatten())

In [14]:
#hidden layer
model.add(Dense(units=1024,activation='relu'))

In [15]:
# output layer 
model.add(Dense(units=8,activation='softmax'))

In [16]:
# Compile model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 128, 128, 32)      896       
                                                                 
 conv2d_1 (Conv2D)           (None, 128, 128, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 64, 64, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 64, 64, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 64, 64, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 32, 32, 64)       0         
 2D)                                                    

### 3.2 Training the Model 

In [18]:
training_history = model.fit(x=training_set,
                             validation_data=validation_set,
                             epochs=10)

Epoch 1/10
79/79 [==============================] - 171s 2s/step - loss: 2.7561 - accuracy: 0.4694 - val_loss: 1.2510 - val_accuracy: 0.5391
Epoch 2/10
79/79 [==============================] - 209s 3s/step - loss: 1.2399 - accuracy: 0.5743 - val_loss: 1.1687 - val_accuracy: 0.6122
Epoch 3/10
79/79 [==============================] - 192s 2s/step - loss: 1.1130 - accuracy: 0.6168 - val_loss: 1.1495 - val_accuracy: 0.6104
Epoch 4/10
79/79 [==============================] - 186s 2s/step - loss: 1.0175 - accuracy: 0.6624 - val_loss: 1.0677 - val_accuracy: 0.6417
Epoch 5/10
79/79 [==============================] - 155s 2s/step - loss: 0.9148 - accuracy: 0.6867 - val_loss: 1.2093 - val_accuracy: 0.6209
Epoch 6/10
79/79 [==============================] - 155s 2s/step - loss: 0.8537 - accuracy: 0.7089 - val_loss: 1.1830 - val_accuracy: 0.6417
Epoch 7/10
79/79 [==============================] - 147s 2s/step - loss: 0.6805 - accuracy: 0.7728 - val_loss: 1.1311 - val_accuracy: 0.6626
Epoch 8/10
79